const INVALID_WIKIPEDIA_URL_ERROR_MSG = 'Invalid Wikipedia URL';
const INTERNAL_SERVER_ERROR_MSG = 'Internal Server Error';
const METHOD_NOT_ALLOWED_ERROR_MSG = 'Method Not Allowed';

export {
    INVALID_WIKIPEDIA_URL_ERROR_MSG,
    INTERNAL_SERVER_ERROR_MSG,
    METHOD_NOT_ALLOWED_ERROR_MSG
};